name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker container
        run: docker build -t mc-fastpg:test .

      # Download test data only if no cache is present
      - name: Download test data
        run: |
          mkdir ~/data
          cd ~/data
          curl -f -o unmicst-exemplar-001_cell.csv \
            https://mcmicro.s3.amazonaws.com/ci/unmicst-exemplar-001_cell.csv
          
      - name: Test the container
        run: |
          cd ~/data
          docker run -v "$PWD":/data mc-fastpg:test /bin/bash -c "cd /data; \
            python3 /app/cluster.py -c -i /data/unmicst-exemplar-001_cell.csv -o /data/"

      # If the action is successful, the output will be available as a downloadable artifact
      - name: Upload processed result
        uses: actions/upload-artifact@v2
        with:
          name: exemplar-001-fastpg
          path: |
            ~/data/*.csv
            ~/data/qc/**
